### ISSUE TITLE
'Error: config.ini not found'

### ISSUE THREAD

**Issue by morphtown** [cternes/Lychee-RSS#1]
Howdy! So far I didn't pass this error.

**Comment by cternes** [comment]
Can you see the file config.ini in directory /lychee/plugins/rss? It should normally be there if you do a git clone from the repository.

**Comment by morphtown** [comment]
Am 04.09.2014 17:46, schrieb cternes:

**Comment by cternes** [comment]
Have you checked the file permissions? The file should be readable by the webserver.
What does the apache error log say?
Under which environment are you working (Linux, Windows, Mac)?

**Comment by morphtown** [comment]
Am 05.09.2014 11:08, schrieb cternes:

**Comment by cternes** [comment]
I've switched the file_exists statement by is_readable. Could you try if that helps you?

The only thing I could imagine right now is the safe_mode. Is [safe_mode](http://php.net/manual/de/ini.sect.safe-mode.php) enabled on your server?

**Comment by morphtown** [comment]
Am 16.09.2014 18:14, schrieb cternes:
