### ISSUE TITLE
correct name of plugin-folder

### ISSUE THREAD

**Issue by hitam4450** [cternes/Lychee-RSS#3]
I installed manually the lychee-RSs plugin, however i do not know the exact name of the directory, holding all the necessary file.: lychee-rss or lycheerss. Both folders do  not work, that means I could not see any pics in the RSS reader (liferea).

regards, hitam4450

**Comment by cternes** [comment]
Try naming the folder "rss" and then navigate to http://myserver/lychee/plugins/rss

Check if you have any errors in the logs.

**Comment by hitam4450** [comment]
Hi, I received a < 404 - Not Found > error message in the webpage!
regards, hitam4450

**Comment by hitam4450** [comment]
I am using https including a self signed certificate on my website!

**Comment by hitam4450** [comment]
For another trial I added the rss feed into the news app of OC 8.03, running on the same server, under the same webserver, etc. and it ends upgiving me an error message telling me : there is a problem with the certificate! (like above with lifrerea on my notebook!)

**Comment by cternes** [comment]
If lychee is running fine through https, lychee-rss should also running fine.

If you receive a 404 you probably accessing the wrong url.

**Comment by hitam4450** [comment]
![bildschirmfoto vom 2015-05-21 21 20 19](https://cloud.githubusercontent.com/assets/9738727/7757021/71154990-ffff-11e4-994c-953eec049aac.png)
![bildschirmfoto vom 2015-05-21 21 21 32](https://cloud.githubusercontent.com/assets/9738727/7757020/7112cd8c-ffff-11e4-95b5-d5ecf6c9f325.png)

Enclosed you'll find 2 screen shots for your reference!

**Comment by hitam4450** [comment]
It still does not work !

regards, hitam4450

**Comment by hitam4450** [comment]
![bildschirmfoto vom 2015-05-21 21 35 23](https://cloud.githubusercontent.com/assets/9738727/7757264/546aeb4a-0001-11e5-82f8-0c1cd57d6f09.png)
Sorry, was a typo in the URL.....but still does not work properly!

**Comment by hitam4450** [comment]
drwxr-xr-x 3 www-data www-data 4096 Mai 21 11:19 rss

**Comment by cternes** [comment]
Your url looks strange to me, could you try the following url:
https://192.168.175.4/lychee.ibt-global.net/plugins/lychee-rss

**Comment by hitam4450** [comment]
Hi, yes it worked fine. However i made a mistake by clicking on the option  : Always import feeds by....!

Do you have any idea how to change that ??
Thanks & regards, hitam4450

**Comment by hitam4450** [comment]
Hi, I received a page including the option to subscribe to the feed offered.

Thanks for the help. I added to feed to lieferea. After that, i added some picture to lychee, but no reference in liferea, even after updating the feed.

regards, hitam4450

**Comment by cternes** [comment]
The feed only works for public photos. Please make sure that your photos are public.
