### ISSUE TITLE
Fatal error: class Database not found

### ISSUE THREAD

**Issue by zikamatej** [cternes/Lychee-RSS#7]
Hi, 
I am experiencing problems with your plugin for Lychee.
When I enter the RSS page (`http://foto.sosna.info/plugins/rss/?format=json`) I get this error:

``` html
<br />
<b>Fatal error</b>:  Class 'Database' not found in <b>/data/web/virtuals/123734/virtual/www/subdom/foto/plugins/rss/DataProvider.php</b> on line <b>13</b><br />
```

When I open just `http://foto.sosna.info/plugins/rss/` It wants me to download an rss file.
![error](https://cloud.githubusercontent.com/assets/17402658/13905304/51c38b40-eebc-11e5-947d-8116ae609fd2.PNG)
Thanks

**Comment by cternes** [comment]
Does lychee work for you as expected? Normally this error would occur if you're missing some kind of (mysql) library on your machine.

**Comment by zikamatej** [comment]
It works perfectly :) But I am running it under webhosting, I don't own the server

**Comment by cternes** [comment]
Could you print the output of the lychee diagnostics page (/plugins/check/) here?

**Comment by zikamatej** [comment]
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  3.1.0
DB Version:      030003
System:          Linux
PHP Version:     5.5
MySQL Version:   100021
Imagick:         1
Imagick Active:  0
Imagick Version: 1650
GD Version:      bundled (2.1.0 compatible)
Plugins:         
```

**Comment by Mikaciu** [comment]
I have done a pull request  (#8) for the Database issue ; it's due to the namespaces.

**Comment by cternes** [comment]
Thanks @Mikaciu. I've tested with v3.0.9 and it has worked fine for me.
